client_group_1:
  federate:
    local_update_steps: 1
  data:
    task: imdb
  optimizer:
    type: AdamW
    lr: 3e-5
    weight_decay: 0.01
    grad_clip: 1.0
  scheduler:
    type: step
    warmup_ratio: 0.1
  trainer:
    train_steps: 2000 #5000
    grad_accum_count: 1
  eval:
    metrics: ['acc']
client_group_2:
  federate:
    local_update_steps: 1
  data:
    task: agnews
  optimizer:
    type: AdamW
    lr: 3e-5
    weight_decay: 0.01
    grad_clip: 1.0
  scheduler:
    type: step
    warmup_ratio: 0.1
  trainer:
    train_steps: 2000 #5000
    grad_accum_count: 1
  eval:
    metrics: ['acc']
client_group_3:
  federate:
    local_update_steps: 1
  data:
    task: squad
  optimizer:
    type: AdamW
    lr: 3e-5
    weight_decay: 0.01
    grad_clip: 1.0
  scheduler:
    type: step
    warmup_ratio: 0.1
  trainer:
    train_steps: 2000 #5000
    grad_accum_count: 1
  eval:
    metrics: ['squad']
    n_best_size: 20
    max_answer_len: 30
    null_score_diff_threshold: 0.0
client_group_4:
  federate:
    local_update_steps: 1
  data:
    task: newsqa
  optimizer:
    type: AdamW
    lr: 3e-5
    weight_decay: 0.01
    grad_clip: 1.0
  scheduler:
    type: step
    warmup_ratio: 0.1
  trainer:
    train_steps: 10000 #20000
    grad_accum_count: 1
  eval:
    metrics: ['newsqa']
    n_best_size: 20
    max_answer_len: 30
    null_score_diff_threshold: 0.0
client_group_5:
  federate:
    local_update_steps: 1
  model:
    label_smoothing: 0.1
  data:
    task: cnndm
  optimizer:
    type: AdamW
    lr_enc: 0.002
    lr_dec: 0.2
    weight_decay: 0.0
    grad_clip: 0.0
  scheduler:
    type: noam
    warmup_ratio_enc: 0.4
    warmup_ratio_dec: 0.2
  trainer:
    train_steps: 10000 #20000
    grad_accum_count: 1
  eval:
    metrics: ['cnndm']
  test:
    beam_size: 5
    min_length: 50
    max_length: 200
    block_trigram: True
    alpha: 0.95
client_group_6:
  federate:
    local_update_steps: 1
  model:
    label_smoothing: 0.1
  data:
    task: msqg
  optimizer:
    type: AdamW
    lr_enc: 0.002
    lr_dec: 0.2
    weight_decay: 0.0
    grad_clip: 0.0
  scheduler:
    type: noam
    warmup_ratio_enc: 0.4
    warmup_ratio_dec: 0.2
  trainer:
    train_steps: 10000 #20000
    grad_accum_count: 1
  eval:
    metrics: ['msqg']
  test:
    beam_size: 5
    min_length: 1
    max_length: 100
    block_trigram: True
    alpha: 0.95
