use_gpu: True
device: 0
seed: 12345
outdir: exp/fedavg/v5/
federate:
  mode: standalone
  method: fedavg
  local_update_steps: 1
  batch_or_epoch: epoch
  total_round_num: 50
  client_num: 18
  num_grouped_clients: [1, 3, 3, 2, 5, 4]
  save_to: ckpt/
#  load_from: exp/pfednlp_contrast/pretrain/fedavg/50_20/ckpt
data:
  type: fednlp_data
  root: /mnt/dongchenhe.dch/datasets/fednlp/v5/
  max_seq_len:
    imdb: 128
    agnews: 128
    squad: 384
    newsqa: 384
    cnndm: 384
    msqg: 384
  max_query_len:
    squad: 128
    newsqa: 128
  trunc_stride:
    squad: 128
    newsqa: 128
  max_tgt_len:
    cnndm: 128
    msqg: 64
  all_batch_size:
    imdb: 32
    agnews: 32
    squad: 32
    newsqa: 32
    cnndm: 32
    msqg: 32
  num_workers: 0
  cache_dir: cache/v5/
model:
  type: fednlp_model
  bert_type: google/bert_uncased_L-2_H-128_A-2
  num_dec_layers: 1
  num_labels:
    imdb: 2
    agnews: 4
    squad: 2
    newsqa: 2
personalization:
  local_param: ['classifier', 'decoder', 'generator']
trainer:
  type: fednlp_trainer
  disp_freq: 50
  val_freq: 100000000  # eval freq across batches
eval:
  split: ['test']
  report: ['group_avg']
  freq: 100000000  # eval freq across rounds
test:
  temp_dir: temp
