use_gpu: True
device: 7
seed: 12345
federate:
  mode: standalone
  method: local
  local_update_steps: 1
  batch_or_epoch: epoch
  total_round_num: 1
  client_num: 1
data:
  type: mydata
  dir:
    imdb: /mnt/dongchenhe.dch/datasets/imdb/
    squad: /mnt/dongchenhe.dch/datasets/squad2.0/
    cnndm: /mnt/dongchenhe.dch/datasets/cnndm/
  max_seq_len:
    imdb: 128
    squad: 128
    cnndm: 512
  max_query_len: 64
  trunc_stride: 32
  max_tgt_len: 128
  all_batch_size:
    imdb: 32
    squad: 32
    cnndm: 4
  num_workers: 8
  cache_dir: cache
model:
  type: mynet
  bert_type: bert-base-uncased
  dec_d_ffn: 2048
  dec_dropout_prob: 0.2
  num_dec_layers: 6
  num_labels: [2]
optimizer:
  type: AdamW
  lr: 3e-5
  weight_decay: 0.01
  grad_clip: 1.0
scheduler:
  type: step
  warmup_ratio: 0.1
criterion:
  type: CrossEntropyLoss
trainer:
  type: mytrainer
  disp_freq: 50
  val_freq: 100000 #100000000
  grad_accum_count: 1
  save_dir: ckpt
test:
  temp_dir: temp
